name: 编译

on:
  #push:
  #  branches:
  #    - master
  #pull_request:
  #  branches:
  #    - master
  workflow_dispatch:

jobs:
  Linux:
    name: Linux 编译
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 使用 Adoptium Temurin JDK
          java-version: '21'

      # 安装 Python 3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 支持 3.9 到 3.13 的 Python 版本

      # 安装 Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'

      # 安装构建工具 (Linux 环境)
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc g++

      # 下载并安装构建依赖
      - name: Fetch build dependencies
        run: |
          gradle -I gradle/support/fetchDependencies.gradle

      # 构建 Ghidra
      - name: Build Ghidra
        run: |
          gradle buildGhidra

      # 保存构建结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-build
          path: build/dist/

  Windows:
    name: Windows 编译
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 使用 Adoptium Temurin JDK
          java-version: '21'

      # 设置 Python 3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 支持 3.9 到 3.13 的 Python 版本

      # 安装 Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'

      # 安装 Windows 构建工具
      - name: Install Windows build tools
        run: |
          choco install visualstudio2017buildtools --yes --no-progress
          choco install visualstudio2017-workload-vctools --yes --no-progress
          choco install make --yes --no-progress

      # 下载并安装构建依赖
      - name: Fetch build dependencies
        run: |
          gradle -I gradle/support/fetchDependencies.gradle --parallel --max-workers=8

      # 构建 Ghidra
      - name: Build Ghidra
        run: |
          gradle buildGhidra --parallel --max-workers=8

      # 保存构建结果
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-build
          path: build/dist/
